# Generated by Django 6.0.4 on 2026-05-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0008_alter_category_created_at_alter_category_updated_at_and_more",
        ),
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["-is_primary", "order", "created_at"],
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
        # Старые ProductImage хранили путь к локальному файлу. После перехода на
        # FK shared.Image те записи не имеют корректного аналога, поэтому в dev
        # их удаляем — кладовщик загрузит файлы заново через новое хранилище.
        migrations.RunSQL(
            sql="DELETE FROM products_productimage;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="category",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                help_text="Изображение плитки категории в каталоге.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="shared.image",
                verbose_name="Постер",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_parameters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Список разделов описания товара. Формат: [{"title": "Общие характеристики", "parameters": "<p>HTML</p>"}].',
                verbose_name="Параметры описания",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="technical_specifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Список групп характеристик. Формат: [{"title": "Электрические параметры", "specifications": [{"label": "Напряжение", "value": "220 В"}]}].',
                verbose_name="Технические характеристики",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок в галерее. Меньшее значение — раньше.",
                verbose_name="Порядок",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Уникальный идентификатор в URL /catalog/{slug}.",
                max_length=255,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="availability",
            field=models.CharField(
                choices=[
                    ("in_stock", "В наличии"),
                    ("out_of_stock", "Нет в наличии"),
                    ("on_request", "Под заказ"),
                ],
                default="in_stock",
                help_text="Доступность товара: в наличии, нет в наличии, под заказ",
                max_length=20,
                verbose_name="Доступность",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Бренд"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Текст карточки товара (без HTML).",
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Гибкие параметры: размер, цвет, объем и т.д.",
                verbose_name="Гибкие параметры",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Цена в рублях. В API округляется до целого.",
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Артикул (SKU)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Артикул",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                    ("archived", "Архивирован"),
                ],
                default="draft",
                help_text="Статус товара: черновик, опубликован, архивирован",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ForeignKey(
                help_text="Файл изображения из общего хранилища (с webp/avif производными).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="shared.image",
                verbose_name="Изображение",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Главное изображение карточки (poster). Только одно на товар.",
                verbose_name="Главное",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
    ]
