# Generated by Django 6.0.4 on 2026-05-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_migrate_json_to_db_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_parameters',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technical_specifications',
        ),
    ]
