# Generated by Django 6.0.4 on 2026-04-27 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0006_make_price_nullable"),
        (
            "users",
            "0005_rename_cust_roles_cust_123456_idx_customer_ro_custome_df1c5a_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        help_text="Order status: new, processing, confirmed, cancelled, completed",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Contact email for this order (may differ from customer email)",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone for this order",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="Recipient first name", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Recipient last name", max_length=100
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Delivery address")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Order notes or special instructions"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who placed this order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="users.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(
                        help_text="Product name snapshot at time of order",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity ordered"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price snapshot at time of order",
                        max_digits=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product ordered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "order_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["customer"], name="orders_custome_6c3a7f_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_status_762191_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_77e2b9_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="order_items_order_i_26ad88_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"], name="order_items_product_a53db1_idx"
            ),
        ),
    ]
