# Generated by Django 6.0.4 on 2026-04-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0008_alter_customer_options_alter_customerrole_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(help_text='Контактный email для этого заказа (может отличаться от email клиента)', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Контактный телефон для этого заказа', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Клиент, оформивший заказ', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя получателя', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия получателя', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Примечания к заказу или особые инструкции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('completed', 'Выполнен')], default='new', help_text='Статус заказа: новый, в обработке, подтвержден, отменен, выполнен', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(help_text='Название товара на момент заказа', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Количество товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за единицу на момент заказа', max_digits=10),
        ),
    ]
