# Generated by Django 6.0.4 on 2026-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at_alter_order_updated_at_and_more'),
        ('users', '0010_customeroutstandingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', help_text='Способ получения заказа: самовывоз или доставка', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта точки доставки (обязательна при delivery_type=delivery)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Долгота точки доставки (обязательна при delivery_type=delivery)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Уникальный номер заказа в формате NNNNN-X', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес доставки (обязателен при delivery_type=delivery)'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_type'], name='orders_deliver_f9d0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
    ]
