# Generated by Django 6.0.4 on 2026-05-20 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок страницы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание страницы')),
            ],
            options={
                'verbose_name': 'Настройки страницы новостей',
                'verbose_name_plural': 'Настройки страницы новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(help_text="Идентификатор в URL/фильтре. Значение 'all' запрещено.", max_length=64, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Таб новостей',
                'verbose_name_plural': 'Табы новостей',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор в URL /news/{slug}.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', help_text='Краткий plain-text для карточки и баннера single-страницы.', verbose_name='Тизер')),
                ('content', models.TextField(blank=True, default='', help_text='HTML, рендерится через dangerouslySetInnerHTML. Опасные теги вырезаются автоматически на save.', verbose_name='Контент (HTML)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Отображается на фронте; ISO 8601 UTC в API.', verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=16, verbose_name='Статус')),
                ('picture', models.ForeignKey(blank=True, help_text='Постер для карточки и баннера single-страницы.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='Изображение')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newstab', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['status', '-date'], name='news_newsar_status_f796af_idx'), models.Index(fields=['tab', 'status', '-date'], name='news_newsar_tab_id_b34ed2_idx')],
            },
        ),
    ]
