# Generated by Django 6.0.4 on 2026-05-20 11:52

import apps.shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Описание изображения для accessibility и SEO.', max_length=255, verbose_name='Альтернативный текст')),
                ('source_desktop', models.ImageField(help_text='Основной исходный файл (jpg или png). Бекенд автоматически сгенерирует webp/avif производные.', upload_to=apps.shared.models._upload_source_desktop, verbose_name='Исходник (desktop)')),
                ('source_mobile', models.ImageField(blank=True, help_text='Опциональный исходник для медиа max-width: 767px. Если не задан — фронт использует desktop-вариант.', null=True, upload_to=apps.shared.models._upload_source_mobile, verbose_name='Исходник (mobile)')),
                ('webp_desktop', models.FileField(blank=True, help_text='Генерируется автоматически после сохранения исходника.', null=True, upload_to=apps.shared.models._upload_derived, verbose_name='Производный WebP (desktop)')),
                ('avif_desktop', models.FileField(blank=True, help_text='Генерируется автоматически после сохранения исходника.', null=True, upload_to=apps.shared.models._upload_derived, verbose_name='Производный AVIF (desktop)')),
                ('webp_mobile', models.FileField(blank=True, null=True, upload_to=apps.shared.models._upload_derived, verbose_name='Производный WebP (mobile)')),
                ('avif_mobile', models.FileField(blank=True, null=True, upload_to=apps.shared.models._upload_derived, verbose_name='Производный AVIF (mobile)')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-created_at'],
            },
        ),
    ]
