# Generated by Django 6.0.4 on 2026-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', help_text='Российский формат, например +7 (999) 999-99-99.', max_length=32, verbose_name='Телефон')),
                ('message', models.TextField(help_text='1..2000 символов.', verbose_name='Сообщение')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP отправителя на момент создания обращения (для антиспама).', null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Дата отметки об обработке менеджером.', null=True, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feedback_fe_created_d924f8_idx'), models.Index(fields=['processed_at'], name='feedback_fe_process_5a652a_idx')],
            },
        ),
    ]
