# Generated by Django 6.0.4 on 2026-04-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_roles_to_catalog_manager'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerrole',
            new_name='customer_ro_custome_df1c5a_idx',
            old_name='cust_roles_cust_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='customerrole',
            new_name='customer_ro_role_id_248606_idx',
            old_name='cust_roles_role_789abc_idx',
        ),
        migrations.RenameIndex(
            model_name='customerrole',
            new_name='customer_ro_assigne_abd951_idx',
            old_name='cust_roles_assigned_def012_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='roles_name_a96913_idx',
            old_name='roles_name_9f2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='roles_is_acti_723ee4_idx',
            old_name='roles_is_active_7c3d4e_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='customers', through='users.CustomerRole', through_fields=('customer', 'role'), to='users.role'),
        ),
        migrations.AlterField(
            model_name='customerrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=dict, help_text="JSON object with permissions, e.g., {'create_product': true, 'edit_product': true}"),
        ),
    ]
