# Generated by Django 6.0.4 on 2026-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_order_permissions_to_catalog_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='customerrole',
            options={'verbose_name': 'Роль клиента', 'verbose_name_plural': 'Роли клиентов'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=dict, help_text="JSON объект с разрешениями, например: {'create_product': true, 'edit_product': true}"),
        ),
    ]
