# Generated by Django 6.0.4 on 2026-05-20 12:02

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customer_options_alter_customerrole_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Имя пользователя для отображения (2..64 символа). Заполняется при регистрации.', max_length=64),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.users.models._generate_reset_token, max_length=64, unique=True, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, help_text='Если заполнен — токен уже был использован и больше не валиден.', null=True, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='users.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Токен сброса пароля',
                'verbose_name_plural': 'Токены сброса пароля',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='password_re_token_060a1f_idx'), models.Index(fields=['customer', 'used_at'], name='password_re_custome_ec335c_idx')],
            },
        ),
    ]
