# Generated by Django 6.0.4 on 2026-05-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customer_username_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOutstandingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(help_text='JWT ID — уникальный идентификатор refresh-токена.', max_length=255, unique=True, verbose_name='JTI')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Выпущен')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Заполнен — токен помещён в blacklist.', null=True, verbose_name='Отозван')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_tokens', to='users.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Активный refresh-токен',
                'verbose_name_plural': 'Активные refresh-токены',
                'db_table': 'customer_outstanding_tokens',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['customer', 'revoked_at'], name='customer_ou_custome_22d3ed_idx'), models.Index(fields=['jti'], name='customer_ou_jti_2cd9d8_idx')],
            },
        ),
    ]
