# Generated by Django 6.0.4 on 2026-05-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Внутреннее название блока для админки",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero/CTA блок"),
                            ("text", "Текст"),
                            ("faq", "FAQ (вопросы-ответы)"),
                            ("features", "Преимущества"),
                            ("gallery", "Галерея"),
                            ("reviews", "Отзывы"),
                            ("banner", "Баннер"),
                            ("video", "Видео"),
                            ("statistics", "Статистика/Цифры"),
                            ("contacts", "Контакты"),
                        ],
                        help_text="Выберите тип контентного блока",
                        max_length=20,
                        verbose_name="Тип блока",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Данные блока в формате JSON. Структура зависит от типа блока.",
                        verbose_name="Содержимое блока",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован")],
                        default="draft",
                        help_text="Черновик — блок не отображается на сайте. Опубликован — блок виден на сайте.",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок контента",
                "verbose_name_plural": "Блоки контента",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок страницы",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор для URL. Автоматически генерируется из заголовка.",
                        max_length=255,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SEO-заголовок для поисковых систем. Если не указан, используется заголовок страницы.",
                        max_length=255,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="SEO-описание для поисковых систем.",
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для предпросмотра при отправке ссылки в соцсетях.",
                        null=True,
                        upload_to="pages/og/",
                        verbose_name="OG изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок отображения блока на странице.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_blocks",
                        to="pages.contentblock",
                        verbose_name="Блок",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_blocks",
                        to="pages.page",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок на странице",
                "verbose_name_plural": "Блоки на странице",
                "ordering": ["order"],
                "unique_together": {("page", "block")},
            },
        ),
        migrations.AddField(
            model_name="page",
            name="blocks",
            field=models.ManyToManyField(
                help_text="Контентные блоки, отображаемые на этой странице.",
                related_name="pages",
                through="pages.PageBlock",
                through_fields=("page", "block"),
                to="pages.contentblock",
                verbose_name="Блоки",
            ),
        ),
    ]
