# Generated by Django 6.0.4 on 2026-05-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Подпись таба на витрине, например «Электроинструмент».', max_length=255, verbose_name='Название группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа витрины',
                'verbose_name_plural': 'Группы витрины',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageShowcaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Товар в группе витрины',
                'verbose_name_plural': 'Товары в группах витрины',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.CharField(choices=[('privacy-policy', 'Политика конфиденциальности'), ('user-agreement', 'Пользовательское соглашение'), ('personal-data-consent', 'Согласие на обработку персональных данных')], max_length=64, primary_key=True, serialize=False, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('last_updated', models.CharField(help_text='Формат ДД.ММ.ГГГГ (как отображается на фронте).', max_length=10, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Юридический документ',
                'verbose_name_plural': 'Юридические документы',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_id', models.SlugField(help_text='Уникален в пределах документа. Используется для TOC и якорей.', max_length=64, verbose_name='Якорь (id)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок раздела')),
                ('content', models.TextField(help_text='Plain text. Абзацы разделяются двумя переводами строки.', verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел документа',
                'verbose_name_plural': 'Разделы документа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('banner_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Баннер · заголовок')),
                ('banner_description', models.TextField(blank=True, default='', verbose_name='Баннер · описание')),
                ('content', models.TextField(blank=True, default='', help_text='HTML рендерится на фронте через dangerouslySetInnerHTML.', verbose_name='Контент (HTML)')),
                ('banner_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='Баннер · постер')),
            ],
            options={
                'verbose_name': 'Страница «О компании»',
                'verbose_name_plural': 'Страница «О компании»',
            },
        ),
        migrations.CreateModel(
            name='BuyersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('banner_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Баннер · заголовок')),
                ('banner_description', models.TextField(blank=True, default='', verbose_name='Баннер · описание')),
                ('content', models.TextField(blank=True, default='', help_text='HTML рендерится на фронте через dangerouslySetInnerHTML.', verbose_name='Контент (HTML)')),
                ('banner_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='Баннер · постер')),
            ],
            options={
                'verbose_name': 'Страница «Покупателям»',
                'verbose_name_plural': 'Страница «Покупателям»',
            },
        ),
        migrations.CreateModel(
            name='FeedbackPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('section_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Секция · заголовок')),
                ('section_description', models.TextField(blank=True, default='', verbose_name='Секция · описание (HTML)')),
                ('news_cta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Новости · заголовок')),
                ('news_cta_description', models.TextField(blank=True, default='', verbose_name='Новости · описание')),
                ('news_cta_button_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Новости · текст кнопки')),
                ('news_cta_button_href', models.CharField(blank=True, default='', max_length=500, verbose_name='Новости · ссылка кнопки')),
                ('news_cta_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='Новости · постер')),
            ],
            options={
                'verbose_name': 'Страница «Обратная связь»',
                'verbose_name_plural': 'Страница «Обратная связь»',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('hero_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero · заголовок')),
                ('hero_description', models.TextField(blank=True, default='', help_text='Допустимы теги br, p, strong, em и т. п. (см. sanitize_html).', verbose_name='Hero · описание (HTML)')),
                ('hero_button_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero · текст кнопки')),
                ('hero_button_href', models.CharField(blank=True, default='', max_length=500, verbose_name='Hero · ссылка кнопки')),
                ('about_title', models.CharField(blank=True, default='', max_length=255, verbose_name='О компании · заголовок')),
                ('about_content', models.TextField(blank=True, default='', verbose_name='О компании · содержимое (HTML)')),
                ('reviews_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Отзывы · заголовок')),
                ('showcase_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Витрина · заголовок')),
                ('showcase_button_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Витрина · текст кнопки')),
                ('showcase_button_href', models.CharField(blank=True, default='', max_length=500, verbose_name='Витрина · ссылка кнопки')),
                ('news_cta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Новости · заголовок')),
                ('news_cta_description', models.TextField(blank=True, default='', verbose_name='Новости · описание')),
                ('news_cta_button_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Новости · текст кнопки')),
                ('news_cta_button_href', models.CharField(blank=True, default='', max_length=500, verbose_name='Новости · ссылка кнопки')),
                ('about_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='О компании · постер')),
                ('hero_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='Hero · постер')),
                ('news_cta_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='Новости · постер')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='HomePageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_reviews', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Отзыв на главной',
                'verbose_name_plural': 'Отзывы на главной',
                'ordering': ['order'],
            },
        ),
    ]
