# Generated by Django 6.0.4 on 2026-05-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('products', '0009_alter_productimage_options_remove_category_image_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagereview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='home_pages', through='pages.HomePageReview', to='reviews.review', verbose_name='Отзывы'),
        ),
        migrations.AddField(
            model_name='homepageshowcase',
            name='home_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcases', to='pages.homepage'),
        ),
        migrations.AddField(
            model_name='homepageshowcaseproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product'),
        ),
        migrations.AddField(
            model_name='homepageshowcaseproduct',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_products', to='pages.homepageshowcase'),
        ),
        migrations.AddField(
            model_name='homepageshowcase',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='home_showcases', through='pages.HomePageShowcaseProduct', to='products.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='legalsection',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.legaldocument', verbose_name='Документ'),
        ),
        migrations.AlterUniqueTogether(
            name='homepagereview',
            unique_together={('home_page', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='homepageshowcaseproduct',
            unique_together={('showcase', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='legalsection',
            unique_together={('document', 'anchor_id')},
        ),
    ]
