# Generated by Django 6.0.4 on 2026-05-20 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(help_text='Короткий заголовок отзыва.', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Текст отзыва')),
                ('grade', models.PositiveSmallIntegerField(help_text='Целое число от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('author_full_name', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть отзыв со всех страниц.', verbose_name='Опубликован')),
                ('author_icon', models.ForeignKey(blank=True, help_text='Опциональная аватарка автора отзыва.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.image', verbose_name='Аватар автора')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
